### ISSUE TITLE
Block number doesn't get updated

### ISSUE THREAD

**Issue by carterqw2** [celo-org/celostats-frontend#65]
![image](https://user-images.githubusercontent.com/20768968/94965520-f2b23600-04fb-11eb-98a0-f611be8ee674.png)
How to reproduce:
1. Open https://baklava-celostats.celo-testnet.org/
2. Wait 30 seconds.
3. Notice that the block number on the left stopped updating.

**Comment by aaronmgdr** [comment]
couldnt reproduce

**Comment by carterqw2** [comment]
@aaronmgdr you can't reproduce it on Baklava or locally?

**Comment by aaronmgdr** [comment]
I believe i tried both
